### ISSUE TITLE
More orderly functions

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#19]
Internal functions are mixed in the middle between external and public functions; the fallback function and constructor are also in the middle among.  More ordering would help readers identify which functions they can call, and to find the "specials" (constructor and fallback).

How's this suggestion for ordering functions?

- constructor
- fallback function
- external
- public
- internal
- private

Fallback function is the first, after the constructor, since it is `external`.  Sort the external/public functions by placing the `constant` ones last, ie just before the `internal` functions.

**Comment by Georgi87** [comment]
I agree, constructor- and fallback-function should be on top. Not sure if sorting the others by visibility is better than sorting by context. If sorted by visibility I agree to your proposed order. Just one change: I would separate constant functions and put them last. Some of them might be removed from the contract soon: https://github.com/ethereum/EIPs/issues/144

I thought also about making all external functions other than the fallback-function and functions only used by web3 public. Mostly because future inheriting contracts may need to access them and cannot if they are external.

**Comment by ethers** [comment]
@Georgi87 All your feedback sounds good and the PR has been updated with them.

**Comment by Georgi87** [comment]
Thanks, PR was merged.
