### ISSUE TITLE
No event when executeTransaction fails

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#25]
There's no event or return value when executeTransaction fails.  There's only an event when it succeeds, and it can require more steps to debug when executeTransaction fails eg was the txhash wrong, or it's not confirmed yet.  Doesn't look like there's a 3rd case of failure (apart from OOG), or is there?

**Comment by Georgi87** [comment]
With the current implementation an error is thrown if the execution fails, so no event would be logged or return would be available. Changing this behaviour to not use `throw` and returning a boolean instead would not really add much info for the user. `executeTransaction` is triggered with every single call of `confirmTransaction`. So whenever there is a `Confirmation` event without an `Execute` event it is clear that the confirmation threshold was not reached. If `tx.destination.call.value(tx.value)(tx.data)` is failing, no additional info about why it failed is available. So a return false instead of a throw, in this case, would not add much information. Showing the user data of transactions, which are executed/failing should be part of the UI.

**Comment by ethers** [comment]
I meant this more when the wrong txhash is passed to executeTransaction.  There's no event that someone can see to find out that eg the destination had typo and so the txhash is wrong (similar to #28).

I think the question is why is `executeTransaction` `public`?  When does it need to be called by itself without `confirmTransaction`?

**Comment by Georgi87** [comment]
I think this is more a UI task to show the user the transaction attributes and he is aware of what he is signing. Do you have an idea on how to improve the programmatically?

There is one situation when `executeTransaction` should be called without `confirmTransaction`. Assuming a transaction needs 2 confirmations and has already 1. Now the # required confirmations is lowered to 1. The transaction can now be executed as it already has the required number of confirmations with `executeTransaction`. Otherwise, someone would have to call `revokeConfirmation` and `confirmTransaction` to trigger `executeTransaction`.

**Comment by ethers** [comment]
Here's some ideas but I'm not that convinced of them either:
* log more params, like Execution(transactionHash, destination); // could also add value, and data but it would get more costly in gas
* add an event like NonExecution(...)  (which would be emitted in the "else" clause)

Thanks for the executeTransaction scenario (missed it); probably worthwhile to have a double-check with an automated test.

**Comment by Georgi87** [comment]
I think the tx hash is sufficient as the UI can easily get all tx information using transactions(tx hash).

The NonExecution event would help to identify failed executions and would also keep confirmations as the current implementation rolls back the last confirmation. Adding it makes sense. I would probably name it `ExecutoinFailure(tx_hash)`. What do you think? Adding a test for executing a tx after requirements changed is a good idea as well.

**Comment by Georgi87** [comment]
added ExecutoinFailure in 32aa249bd66bcd92a2d3c9b6fb77bef441d0360d

Added issue for missing test: https://github.com/ConsenSys/MultiSigWallet/issues/29

**Comment by ethers** [comment]
> would also keep confirmations as the current implementation rolls back the last confirmation. 
Interesting.  There is/was a "code smell" with confirmTransaction doing "2" things: maybe this is the end of it and it's all ok.

Event name sounds good.

**Comment by ethers** [comment]
FYI my comment above was:
> add an event like NonExecution(...) (which would be emitted in the "else" clause)

I should have clarified that the "else" clause I meant was:
```
if (isConfirmed(transactionHash)) {
}
else {
  // ExecutionFailure(transactionHash);
}
```

`ExecutionFailure` event would be added to "else" clause of `isConfirmed(transactionHash)`.
I did not expect the `throw` here
```
if (!tx.destination.call.value(tx.value)(tx.data))
                throw;
```
to be replaced with `ExecutionFailure` because philosophically it replaces more-safe code, `throw` with less-safe code `return false`.

**Comment by ethers** [comment]
Also, my comment on https://github.com/ConsenSys/MultiSigWallet/issues/25#issuecomment-265927404 was supposed to be formatted as:

> would also keep confirmations as the current implementation rolls back the last confirmation.

Interesting. There is/was a "code smell" with confirmTransaction doing "2" things: maybe this is the end of it and it's all ok.

Event name sounds good.

======

Removing the `throw` was a code smell that did turn out to be exploitable in https://github.com/ConsenSys/MultiSigWallet/issues/35

**Comment by Georgi87** [comment]
This else clause would not add much value as the event `Confirmation` without any execution event (`Execution` or `ExecutionFailure`) has the same meaning.

```
if (isConfirmed(transactionHash)) {
}
else {
  // ExecutionFailure(transactionHash);
}
```
