### ISSUE TITLE
Bypass the daily limit

### ISSUE THREAD

**Issue by Georgi87** [ConsenSys/MultiSigWallet#35]
This bug was found as part of the Gnosis bug bounty.

Call:
`submitTransaction(yourAdress,dailylimit,0,0)`
It gives you the daily limit.
Then call
`submitTransaction(bullshitAddress,2^256-dailylimit,0,0)`
The transaction won't be executed because the call will fail, however, spentToday will be reset to 0.

**Comment by Georgi87** [comment]
Fixed in 61ee12bd163eaa006e84c8eb1411e14119f72f7c

**Comment by ethers** [comment]
To auditors and bounty hunters, the overflow bug was a good catch and you may also want to look around the ramifications of this commit:
https://github.com/ConsenSys/MultiSigWallet/commit/6b1c2a02e866bb2702731a2e6dc3b437ed0b46d3

For example, by changing from `throw` to using `return false`, it's what allowed the effects of the overflow (which overflows the spendAmount to zero) to remain in effect, instead of being reverted.  (`send()` with such a high `tx.value` would fail and prior code would lead to `throw` and reversion.)
